# Generated by Django 4.2.14 on 2024-07-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rename_bd_bb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-published'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Товар'),
        ),
    ]
