import React from 'react'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import ReactQueryClientProvider from '../components/ReactQueryClientProvider';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [queryClient] = React.useState(() => new QueryClient())

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ReactQueryClientProvider>
            {children}
          </ReactQueryClientProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
